description: Saskatchewan low income tax credit base for the head.
values:
  2023-07-01: 380
metadata:
  unit: currency-CAD
  label: Saskatchewan low income tax credit base 
  reference:
  - title: Saskatchewan - Low-Income Tax Credit
    href: https://www.saskatchewan.ca/residents/taxes-and-investments/tax-credits/low-income-tax-credit
