description: Northwest Territories provides the following Basic Personal Amount.
values:
  2023-01-01: 16_593
metadata:
  unit: currency-CAD
  period: year
  label: Northwest Territories Basic Personal Amount
  reference:
    - title: Northwest Territories Personal Tax Credits Return - Basic Personal Amount
      href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1nt/td1nt-23e.pdf
    - title: 2023 Northwest Territories Personal Tax Credits Return - Basic Personal Amount
      href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1nt/td1nt-23e.pdf
