description: Alberta provides this amount under the disability credit. 
values:
  2022-01-01: 16_201
metadata:
  unit: currency-CAD
  period: year
  label: Alberta disability credit amount
  reference:
  - title: Alberta disability credit base amount - Section 4
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/td1ab/td1ab-23e.pdf#page=1
  - title: Alberta Personal Income Tax Act - Section 13.1
    href: https://kings-printer.alberta.ca/1266.cfm?page=a30.cfm&leg_type=Acts&isbncln=9780779842674
