description: Canada allows for this base disability amount.
values:
  2021-01-01: 8_662
metadata:
  unit: currency-USD
  period: year
  name: canada_disability_credit_base
  label: Canada disability credit base
  reference:
    - title: Government of Canada - Canada Disability tax credit
      href: https://www.canada.ca/en/revenue-agency/services/tax/individuals/segments/tax-credits-deductions-persons-disabilities/disability-tax-credit/claiming-dtc.html
