description: Onatrio Child Benefit base.
values:
  2022-07-01: 1_509
metadata:
  unit: currency-CAD
  name: ontario_child_benefit_base
  label: ontario child benefit base
  reference:
  - title: Government of Canada - Canada Child Benefit
    href: https://www.canada.ca/en/revenue-agency/services/forms-publications/publications/t4114/canada-child-benefit.html
  - title: Taxation Act Part V 104  
    href: https://www.ontario.ca/laws/statute/07t11?search=child+benefit#BK190