description: Quebec limits its Senior Assistance Credit to seniors at or below this base amount.
values:
  2022-01-01: 2_000 
metadata:
  unit: currency-CAD
  label: Quebec senior assistance credits limit base amount
  reference:
    - title: Revenu Quebec - Amount of the Senior Assistance Tax Credit
      href: https://www.revenuquebec.ca/en/citizens/tax-credits/senior-assistance-tax-credit/amount-of-the-credit/