description: British Columbia disability credit base amount.
values:
  2022-01-01: 8_477
  2023-01-01: 8_986
metadata:
  unit: currency-CAD
  label: British Columbia base disability credit amount
  reference:
  - title: B.C. basic personal income tax credits
    href: https://www2.gov.bc.ca/gov/content/taxes/income-taxes/personal/credits/basic
  - title: Income Tax Act (4.51)
    href: https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/96215_00_multi#section4.51
  - title: Worksheet BC428
    href: https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5010-d/5010-d-22e.pdf#page=1
