description: Manitoba provides this base amount for its Child Tax Benefit.
values:
  2023-01-01: 420 #35 per month
metadata:
  unit: currency-CAD
  label: Manitoba child benefit base
  reference:
    - title: Manitoba child tax benefit 
      href: https://www.gov.mb.ca/fs/eia/mcb.html
    - title: Manitoba child benefit regulation
      href: https://www.gov.mb.ca/fs/eia_manual/regs/4.html
