description: Canada provides a child benefit of this base amount to older children.
values:
  2020-01-01: 5_903
metadata:
  unit: currency-CAD
  name: child_benefit_older_base_amount
  label: Child benefit older base amount
  reference:
  - title: Government of Canada - Canada Child Benefit
    href: https://www.canada.ca/en/revenue-agency/programs/about-canada-revenue-agency-cra/federal-government-budgets/budget-2019-investing-middle-class/canada-training-credit.html
