description: Yukon child fitness fee $1,000 for eligible fees paid for the cost of registration or membership.
values:
  2022-01-01: 1_000
metadata:
  unit: currency-CAD
  label: Yukon child fitness base fee
  reference:
  - title: Children's fitness tax credit
    href: https://www.canada.ca/en/revenue-agency/services/forms-publications/tax-packages-years/general-income-tax-benefit-package/yukon/5011-pc/information-residents-yukon.html#P5_cftc
