description: yukon child benefit base amount.
values:
  2015-01-01: 820
metadata:
  unit: currency-CAD
  label: Yukon child benefit base
  reference:
  - title: Yukon-specific income tax measures
    href: https://yukon.ca/en/yukon-income-tax