description: Alberta provides this base disability credit amount. 
values:
  2022-01-01: 15_284
metadata:
  unit: currency-CAD
  period: year
  label: Alberta disability credit base amount
  reference:
  - title: Alberta Disablitiy credit - Page 2
    href:  https://www.canada.ca/content/dam/cra-arc/formspubs/pbg/5009-d/5009-d-22e.pdf#page=2
